name: Validate JSON

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  validate:
    runs-on: ubuntu-latest
    container: dcycle/json-lint:latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Validate JSON using Docker
      run: json-lint -q games.json
