name: Validate JSON

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  validate:
    runs-on: ubuntu-latest
    #container: dcycle/json-lint:latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Validate JSON using Docker
      uses: addnab/docker-run-action@v3
      with:
        image: dcycle/json-lint:latest
        options: -v ${{ github.workspace }}:/work
        run: |
          echo "Linting games.json"
          jsonlint -q /work/games.json
  integrity:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/powershell:7.4-ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run validation script
        run: pwsh .github/scripts/validate-games.ps1
